In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data.csv")

In [3]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Dhawan,Bool Bhulaiyaa,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath ki Dul,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical,2019,Action,342,8.2

In [7]:
df['Actor']

0         Shah Rukh Khan
1            Salman Khan
2             Aamir Khan
3          Ranbir Kapoor
4          Ranveer Singh
5     Ayushmann Khurrana
6          Rajkummar Rao
7         Hrithik Roshan
8           Akshay Kumar
9          Kartik Dhawan
10          Varun Dhawan
11         Vicky Kaushal
Name: Actor, dtype: str

In [8]:
df[['Actor', 'IMDb']]

                 Actor  IMDb
0       Shah Rukh Khan   7.2
1          Salman Khan   6.0
2           Aamir Khan   8.4
3        Ranbir Kapoor   5.6
4        Ranveer Singh   7.0
5   Ayushmann Khurrana   8.3
6        Rajkummar Rao   7.5
7       Hrithik Roshan   6.5
8         Akshay Kumar   7.0
9        Kartik Dhawan   5.9
10        Varun Dhawan   6.1
11       Vicky Kaushal   8.2

In [9]:
df.loc[1]

Actor                       Salman Khan
Film                    Tiger Zinda Hai
Year                               2017
Genre                            Action
BoxOffice(INR Crore)                565
IMDb                                6.0
Name: 1, dtype: object

In [10]:
df.iloc[1]

Actor                       Salman Khan
Film                    Tiger Zinda Hai
Year                               2017
Genre                            Action
BoxOffice(INR Crore)                565
IMDb                                6.0
Name: 1, dtype: object

In [11]:
df.loc[8, 'IMDb']

np.float64(7.0)

In [12]:
df.info

<bound method DataFrame.info of                  Actor               Film  Year            Genre  \
0       Shah Rukh Khan            Pathaan  2023           Action
1          Salman Khan    Tiger Zinda Hai  2017           Action
2           Aamir Khan             Dangal  2016        Biography
3        Ranbir Kapoor         Brahmastra  2022          Fantasy
4        Ranveer Singh          Padmaavat  2018       Historical
5   Ayushmann Khurrana          Andhadhun  2018         Thriller
6        Rajkummar Rao              Stree  2018    Horror Comedy
7       Hrithik Roshan                War  2019           Action
8         Akshay Kumar         Good Newwz  2019           Comedy
9        Kartik Dhawan     Bool Bhulaiyaa  2022    Horror Comedy
10        Varun Dhawan   Badrinath ki Dul  2017  Romantic Comedy
11       Vicky Kaushal  Uri: The Surgical  2019           Action

    BoxOffice(INR Crore)  IMDb
0                   1050   7.2
1                    565   6.0
2                   2024   8.4
3                    431   5.6
4                    585   7.0
5                    111   8.3
6                    180   7.5
7                    475   6.5
8                    318   7.0
9                    266   5.9
10                   201   6.1
11                   342   8.2  >

In [16]:
df.loc[0:2, ["Actor", "IMDb", "Film"]]

            Actor  IMDb             Film
0  Shah Rukh Khan   7.2          Pathaan
1     Salman Khan   6.0  Tiger Zinda Hai
2      Aamir Khan   8.4           Dangal

In [17]:
df.iloc[0:2, 0:2]

            Actor             Film
0  Shah Rukh Khan          Pathaan
1     Salman Khan  Tiger Zinda Hai

In [18]:
df.at[0, "Actor"]

'Shah Rukh Khan'

In [19]:
df.iat[0, 0]

'Shah Rukh Khan'

In [24]:
df[df["IMDb"]>6]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Varun Dhawan,Badrinath ki Dul,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical,2019,Action,342,8.2

In [27]:
df[(df["IMDb"]>6) & (df["Year"]>2018)]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical,2019,Action,342,8.2

In [29]:
df.query("Year > 2018 and IMDb > 6")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical,2019,Action,342,8.2