In [1]:
import pandas as pd

In [2]:
data = [['harry', 34],['roshan', 57],['lily', 84],['Vashu', 76]]

In [3]:
data

[['harry', 34], ['roshan', 57], ['lily', 84], ['Vashu', 76]]

In [5]:
pd.DataFrame(data, columns=["Name", "Marks"])

     Name  Marks
0   harry     34
1  roshan     57
2    lily     84
3   Vashu     76

In [12]:
data = {"a":[4, 5, 32], "b":[3, 7, 9]}

In [13]:
data

{'a': [4, 5, 32], 'b': [3, 7, 9]}

In [15]:
df = pd.DataFrame(data)

    a  b
0   4  3
1   5  7
2  32  9

In [16]:
import numpy as np

In [18]:
arr = np.array([[1, 2],[5,6]])

In [21]:
df = pd.DataFrame(arr, columns=["A", "B"])

In [22]:
df

   A  B
0  1  2
1  5  6

In [25]:
df = pd.read_excel("data.xlsx")

In [26]:
df

      Name  School  Marks
0  Shubham     SPS     34
1   Joshua     UPS     45
2     Jack     WPS     45
3     Alex     UIS     67
4  Jasmine     RTS     45
5    Rohan     RRY     88
6    Rishi  Luxury     77
7   Aakash     BBL     90

In [27]:
df = pd.read_csv("data.csv")

In [28]:
df

      Name  School  Marks
0  Shubham     SPS     34
1   Joshua     UPS     45
2     Jack     WPS     45
3     Alex     UIS     67
4  Jasmine     RTS     45
5    Rohan     RRY     88
6    Rishi  Luxury     77
7   Aakash     BBL     90

In [31]:
df = pd.read_json("data.json")

In [32]:
df

     name     lang
0    Asim   Python
1  Mukesh  English

In [34]:
df = pd.read_csv("https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv")

In [35]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [36]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [37]:
df.tail()

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [38]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 7.2 KB

In [39]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [41]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='str')

In [42]:
df.shape

(150, 5)