In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data.csv")

In [3]:
df

      Name  School  Marks
0  Shubham     SPS     34
1   Joshua     UPS     45
2     Jack     WPS     45
3     Alex     UIS     67
4  Jasmine     RTS     45
5    Rohan     RRY     88
6    Rishi  Luxury     77
7   Aakash     BBL     90

In [4]:
df = df[df['Marks']<60]

In [5]:
df

      Name School  Marks
0  Shubham    SPS     34
1   Joshua    UPS     45
2     Jack    WPS     45
4  Jasmine    RTS     45

In [6]:
#df.to_csv("data_updates.csv", index=False)

In [7]:
df = pd.read_json("data.json")

In [12]:
df

     name     lang                                            address
0    Asim   Python  {'post': 'kakrahawa bazar', 'city': 'Siddharth...
1  Mukesh  English  {'post': 'kakrahawa bazar', 'city': 'Siddharth...

In [13]:
data = [
  {
    "name": "Asim",
    "lang": "Python",
    "address": {
      "post": "Kakrahawa Bazar",
      "city": "Siddharth Nagar"
    }
  },
  {
    "name": "Mukesh",
    "lang": "English",
    "address": {
      "post": "Kakrahawa Bazar",
      "city": "Siddharth Nagar"
    }
  }
]

In [14]:
df = pd.json_normalize(data)

In [15]:
df

     name     lang     address.post     address.city
0    Asim   Python  Kakrahawa Bazar  Siddharth Nagar
1  Mukesh  English  Kakrahawa Bazar  Siddharth Nagar